import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-5xl mx-auto'>
          <div className="bg-teal-400 px-4 my-8 text-2xl leading-6 text-white font-medium py-8 rounded-md">
            Uni-B : An E-Commerce Platform
          </div>
          {children}
        </div>
      </body>
    </html >
  )
}
